[package]
name = "midinet"
version = "0.1.0"
authors = ["Jack Wrenn <me@jswrenn.com>"]
description = "Fire MIDI events over the network"
license = "MIT"
repository = "https://github.com/jswrenn/midinet"

[dependencies]
alsa = "0.2"
structopt = "0.2"
